// <auto-generated />
namespace ECS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class productTable_updated2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(productTable_updated2));
        
        string IMigrationMetadata.Id
        {
            get { return "202107061111283_productTable_updated2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
