// <auto-generated />
namespace ECS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Required_modified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Required_modified));
        
        string IMigrationMetadata.Id
        {
            get { return "202107051502583_Required_modified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
