// <auto-generated />
namespace ECS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class db_update_all_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db_update_all_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202107070635390_db_update_all_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
